## This set of functions allow to generate a matrix that can be cached and to calculate the inverse.
## Once the inverse has been calculated it is cached, so that it is unnecessary to recalculate it every time the function cacheSolve is called

## This function create a special matrix that can be cached. It is also possible to set and cache the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
  inverse<-NULL
  set<-function(y) {
    x<<-y
    inverse<<-NULL
  }
  get<-function() x
  setInverse<- function(solve) inverse<<-solve
  getInverse<-function() inverse
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## This function receive as parameter the special matrix generated by the above function. If the inverse matrix has been already
#calculated, the function returns the cached data, otherwise it calculates the inverse and caches the result.

cacheSolve <- function(x, ...) {
  inverse<-x$getInverse()
  if(!is.null(inverse)){
    message("getting cached data")
    return(inverse) 
  }
  matrix<-x$get()
  inverse<-solve(matrix)
  x$setInverse(inverse)
  inverse
}
